<!-- ============================================================================
     Copyright (c) 2026 Supratim Sanyal of SANYALnet Labs.
     Proprietary rights reserved except as expressly licensed herein.

     LUDO ARENA
     This file is governed by the SANYALnet Labs Non-Commercial License in the
     root LICENSE file. Non-Commercial use is permitted; Commercial Use and use
     for AI/ML model training are prohibited unless separately authorized.

     Attribution is required: "Based on original work by Supratim Sanyal of
     SANYALnet Labs." See LICENSE for full terms, warranty disclaimer, termination,
     patent, trademark, and governing-law provisions.
     ============================================================================ -->

<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1903;NU1904</WarningsNotAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
