using System.Collections.Immutable;

namespace LudoNimArena.Core;

/// <summary>A legal move generated by the engine.</summary>
public sealed class LegalMove
{
    public string MoveId { get; }
    public string TokenId { get; }
    public int FromProgress { get; }
    public int ToProgress { get; }
    public bool EntersBoard { get; }
    public ImmutableArray<string> Captures { get; }
    public bool LandsSafe { get; }
    public bool Finishes { get; }
    public bool FormsBlockade { get; }

    public LegalMove(string tokenId, int fromProgress, int toProgress,
        bool entersBoard, IEnumerable<string>? captures = null,
        bool landsSafe = false, bool finishes = false, bool formsBlockade = false)
    {
        TokenId = tokenId;
        FromProgress = fromProgress;
        ToProgress = toProgress;
        EntersBoard = entersBoard;
        Captures = captures?.ToImmutableArray() ?? ImmutableArray<string>.Empty;
        LandsSafe = landsSafe;
        Finishes = finishes;
        FormsBlockade = formsBlockade;

        string fromStr = entersBoard ? "yard" : $"track:{fromProgress}";
        string toStr = finishes ? "home" : $"track:{toProgress}";
        MoveId = $"{tokenId}:{fromStr}->{toStr}";
    }

    public override string ToString() => MoveId;
}
