// ============================================================================
// Copyright (c) 2026 Supratim Sanyal of SANYALnet Labs.
// Proprietary rights reserved except as expressly licensed herein.
//
// LUDO ARENA
// This file is governed by the SANYALnet Labs Non-Commercial License in the
// root LICENSE file. Non-Commercial use is permitted; Commercial Use and use
// for AI/ML model training are prohibited unless separately authorized.
//
// Attribution is required: "Based on original work by Supratim Sanyal of
// SANYALnet Labs." See LICENSE for full terms, warranty disclaimer, termination,
// patent, trademark, and governing-law provisions.
// ============================================================================

using System.Collections.Immutable;

namespace LudoNimArena.Core;

/// <summary>A legal move generated by the engine.</summary>
public sealed class LegalMove
{
    public string MoveId { get; }
    public string TokenId { get; }
    public int FromProgress { get; }
    public int ToProgress { get; }
    public bool EntersBoard { get; }
    public ImmutableArray<string> Captures { get; }
    public bool LandsSafe { get; }
    public bool Finishes { get; }
    public bool FormsBlockade { get; }

    public LegalMove(string tokenId, int fromProgress, int toProgress,
        bool entersBoard, IEnumerable<string>? captures = null,
        bool landsSafe = false, bool finishes = false, bool formsBlockade = false)
    {
        TokenId = tokenId;
        FromProgress = fromProgress;
        ToProgress = toProgress;
        EntersBoard = entersBoard;
        Captures = captures?.ToImmutableArray() ?? ImmutableArray<string>.Empty;
        LandsSafe = landsSafe;
        Finishes = finishes;
        FormsBlockade = formsBlockade;

        string fromStr = entersBoard ? "yard" : $"track:{fromProgress}";
        string toStr = finishes ? "home" : $"track:{toProgress}";
        MoveId = $"{tokenId}:{fromStr}->{toStr}";
    }

    public override string ToString() => MoveId;
}
